config/routes.rb
Rails.application.routes.draw do
  resources :media

   devise_for :users, controllers: { registrations: "users/registrations" }
 
    resources :settings do
    collection do
      get 'mark_all_reviewed'
    end
  end
  
  resources :posts, param: :slug
  get '/:slug', to: 'posts#show'
  
  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :posts_medium
  has_many :media, :through => :posts_medium
  belongs_to :user

  validates :title, presence: true

  validates :slug, presence: true,
    uniqueness: true,
    format: /\A[-_a-z0-9]+\Z/

  def to_param
    slug
  end

  def processed_body(truncated = false)
    
    if truncated
      @return = self.body.split('%%more%%').first
    else
      @return = self.body.sub('%%more%%', '')
    end
    
    self.body.scan(/%%media=\d+%%/).each do |s|    
      #@replace = self.body[/%%media=\d+%%/].split('=').last.sub("%%", "")
      @replace = s.split('=').last.sub("%%", "")  # separate out the id of the media
      #@return = self.body.gsub(/%%media=\d+%%/, Medium.find(@replace).m.to_s);
      @return = @return.gsub(s, Medium.find(@replace).m.to_s);
    end
    return @return.html_safe
  end

  def date_short
    return date.strftime("%b %-e, %Y")
  end

  def has_more?
    if self.body.include?('%%more%%')
      true
    else
      false
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  def index
    @posts = Post.order(date: :desc)
  end

  def show
    @post = Post.find_by_slug!(params[:slug])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find_by(slug: params[:slug])
  end

  def create
    @post = Post.new(post_params)
    logger.debug(post_params[:date])
    @post.date = DateTime.strptime(post_params[:date], '%m-%d-%Y %l:%M %P')
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @post = Post.find_by(slug: params[:slug])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find_by_slug(params[:slug])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :date, :username, :body, :slug)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post, { :html => { :class => 'well form-horizontal' } }) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
      <div class="form-group">
        <%= f.label :title, :class => 'col-lg-2 control-label' %>
        <div class="col-lg-10"><%= f.text_field :title, :class => 'form-control' %></div>
      </div>
      <div class="form-group">
        <%= f.label :date, :class => 'col-lg-2 control-label' %>
        <div class="col-lg-10"><%= f.text_field :date, :class => 'form-control', :id => 'datetimepicker' %></div>
      </div>
      <div class="form-group">
        <%= f.label :slug, :class => 'col-lg-2 control-label' %>
        <div class="col-lg-10"><%= f.text_field :slug, :class => 'form-control' %></div>
      </div>
      
      <%= link_to "Add Media", media_path, :target => '_blank' %>
      
      <div class="form-group">
        <%= f.label :body, :class => 'col-lg-2 control-label' %>
        <div class="col-lg-10"><%= f.text_area :body, :rows => 30, :class => 'form-control' %></div>
      </div>
      <div class="actions">
        <%= f.submit 'Submit Post', :class => 'btn btn-primary' %>
      </div>
    </fieldset>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h4 id="headline" class="hidden-xs"><%= Setting.get("site_headline") %></h4>

<hr class="main-separator hidden-xs" />

<% @posts.each do |post| %>
    <div class="post">
        <div class="post-title"><%= link_to post.title, post.slug %></div>
        <div class="post-meta text-muted">
          <div class="post-date"><%= icon("#{Setting.get('meta_glyph')}") %> <%= post.date_short %></div> <div class="post-user"> / <%= post.user.display_name %></div>
        </div>
        <div class="post-body"><%= @markdown.render(post.processed_body(true)).html_safe %></div>
        <% if post.has_more? %>
          <div class="post-more"><%= link_to "Read More...", post %></div>
        <% end %>
        <hr class="post-separator" />
    </div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="post">

  <div class="post-title"><%= @post.title %></div>
  <div class="post-meta text-muted">
    <div><%= icon("#{Setting.get('meta_glyph')}") %> <%= @post.date_short %>  / <%= @post.user.display_name %></div>
  </div>
  
  <div class="post-body"><%= @markdown.render(@post.processed_body).html_safe %>
  
  <% if user_signed_in? %><%= link_to 'Edit', edit_post_path(@post), class: "btn btn-default" %><% end %>

</div>