config/routes.rb
Rails.application.routes.draw do
  resources :media

   devise_for :users, controllers: { registrations: "users/registrations" }
 
    resources :settings do
    collection do
      get 'mark_all_reviewed'
    end
  end
  
  resources :posts, param: :slug
  get '/:slug', to: 'posts#show'
  
  root 'posts#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= Setting.get("site_title") %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to raw("#{icon(Setting.get('main_glyph'))} #{Setting.get("site_title")}"), root_url, :class => "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
          <% if user_signed_in? %>
            <li class="<%= 'active' if current_page?(new_post_path) %>"><%= link_to "New Post", new_post_path %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Settings", settings_path %></li>
				    <li><%= link_to "Change Password", edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
        </ul>
      </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
  </div><!-- /.navbar -->


    <div class="container">
      <% flash.each do |name, msg| %>
        <% if (name == "alert")
              flash_class = "alert alert-danger"
           elsif (name == "warning")
              flash_class = "alert alert-warning"
           else
              flash_class = "alert alert-info"
           end   %>
		        <%= content_tag(:div, sanitize(msg), { :id => "flash_#{name}", :class => flash_class }) %>
		  <% end %>
		        
        <%= yield %>
    </div>
    
    <div id="footer">
      &copy; <%= Date.today.year %> <a href="http://github.com/npazo/cersei">Built on Cersei</a>
    </div>

</body>
</html>